name: Actions 😎

on: [push]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

#       Cache
      - uses: actions/cache@v2
        with:
          path: The Maze
          key: The Maze-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            The Maze

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 'The Maze/'
          targetPlatform: StandaloneWindows
          allowDirtyBuild: true

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
          
      - name: Zip build
        run: |
          pushd build
          zip -r ../../StandaloneWindows64.zip .
          popd

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release user firmware
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            StandaloneWindows64.zip

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     if: startsWith(github.ref, 'refs/tags/')
      #     files: StandaloneWindows64.zip
      #     name: Release ${{ github.ref }}
          
